[workspace]
authors = ["obi <ole.bialas@posteo.de>"]
channels = ["conda-forge"]
name = "iBOTS-Intro-to-EEG-MEG-Analysis-with-MNE-Python"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
register-kernel = "python -m ipykernel install --user --name ibots-eeg-meg"

[dependencies]
python = "3.13.*"
jupyterlab = ">=4.5.2,<5"
jupyterlab-git = ">=0.51.4,<0.52"
jupyterlab-lsp = ">=5.2.0,<6"
jupyterlab_vim = ">=4.1.4,<5"
jupyterlab-spellchecker = ">=0.8.4,<0.9"
python-lsp-server = ">=1.14.0,<2"
pyvistaqt = ">=0.11.3,<0.12"
ipyevents = ">=2.0.4,<3"
trame = ">=3.12.0,<4"
ipywidgets = ">=8.1.8,<9"
trame-vuetify = ">=3.2.0,<4"
trame-vtk = ">=2.10.2,<3"
nibabel = ">=5.3.2,<6"
scikit-learn = ">=1.8.0,<2"
statsmodels = ">=0.14.6,<0.15"
seaborn = ">=0.13.2,<0.14"
scikit-image = ">=0.26.0,<0.27"
openpyxl = ">=3.1.5,<4"

[pypi-dependencies]
ipykernel = ">=7.1.0, <8"
pip = ">=25.3, <26"
mne = ">=1.11.0, <2"
mne-connectivity = ">=0.7.0, <0.8"
ipympl = ">=0.9.8, <0.10"
pyqt5 = ">=5.15.11, <6"
jldracula = ">=0.2.0, <0.3"
autoreject = ">=0.4.3, <0.5"
ipywidgets = ">=8.1.8, <9"
darkdetect = ">=0.8.0, <0.9"
